name: BIT Notice Update (WebVPN + RSS)
on:
  schedule:
    - cron: '*/30 * * * *'  # 每 30 分钟运行（可按需调整）
  workflow_dispatch:  # 手动触发

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取全量历史

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest  

      - name: Configure WebVPN
        run: |
          mkdir -p config
          echo '${{ secrets.PROXY_SECRETS }}' > config/proxy.secrets.json

      - name: Fix dependencies & Integrity
        run: |
          rm -f deno.lock
          deno cache --reload --import-map=deno.jsonc --node-modules-dir=true src/**/*.ts

      - name: Run Update Server
        env:
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }} 
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
        run: deno task update-server

      - name: Deploy RSS to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./output
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: output/

